CalculationOfPoints: Add initial version
gh215/MD.GameDev.cpp pull request #4
Opened 2024-02-15 17:49 UTC by gh215

2024-02-16 17:51 UTC, amavrin requested changes
Попробовал запустить, получил некорректный результат:
```
Добро пожаловать в нашу игру по вычислению средне арифметического Ваших очков
Введите первую сумму очков:
1
Введите первую сумму очков:
2
Введите первую сумму очков:
2
Средне арифметическое очков = 1
```

необходимо каждую программу сопровождать test cases, без него не приму 😉

2024-02-16 20:17 UTC, amavrin commented on chapter-1/CalculationOfPoints/CalculationOfPoints/CalculationOfPoints.cpp
> +    3. Если сумма очков 4 - средне арифметическое будет = 1
Так это же неверно - если сумма очков 4, среднее арифметическое должно быть 4/3 - то есть 1.333...

2024-02-17 20:26 UTC, gh215 commented on chapter-1/CalculationOfPoints/CalculationOfPoints/CalculationOfPoints.cpp
> +    3. Если сумма очков 4 - средне арифметическое будет = 1
Почему неправильно? Там же есть функция round, которая округляет число до меньшего, если дробная часть меньше или большего, если дробная часть пять или больше

2024-02-17 20:55 UTC, amavrin commented on chapter-1/CalculationOfPoints/CalculationOfPoints/CalculationOfPoints.cpp
> +    3. Если сумма очков 4 - средне арифметическое будет = 1
Ну чему равняется среднее арифметическое чисел 1, 1 и 2?
Считаем по формуле: (1+1+2)/3 = 1.33333...
Так что вот так вот :-)

2024-02-17 21:20 UTC, amavrin requested changes
Нужно вспомнить, что мы говорили про целочисленные вычисления и про вычисления с плавающей точкой. В условии задачи ничего не сказано про округление до целого, поэтому нужно считать "честно" - как в математике.

2024-02-23 15:52 UTC, amavrin approved these changes
LGTM :-)

2024-03-03 16:04 UTC, merged